apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-bundle-overriding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-bundle-overriding
    app.kubernetes.io/part-of: test-app-hhbo
  name: build-suite-test-bundle-overriding
  namespace: e2e-test-bmkj
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: build-suite-test-bundle-overriding
status:
  loadBalancer: {}
